# docker-compose-server.yml (운영 서버용)

services:
  backend:
    image: ${DOCKER_USERNAME}/tem-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - ACCESS_KEY=${ACCESS_KEY}
      - REFRESH_KEY=${REFRESH_KEY}
      - SERVER_PORT=8080
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/tem-frontend:latest
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
