server:
  port: 8080

spring:
  application:
    name: travel-budget

  profiles:
    active: prod
---
# dev profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url:
    username:
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework.security: TRACE

---
# prod profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: validate