spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    key:
      AccessKey: ${ACCESS_KEY}
      RefreshKey: ${REFRESH_KEY}
logging:
  level:
    org.springframework.security: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always

  prometheus:
    metrics:
      export:
        enabled: true